# Setup
title:        Development Blog
tagline:      Deep Learning and Learning Jazz
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Michael Seaman
  url:        https://github.com/MichaelSeaman

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
